stages:
    - build
    - deploy

image: docker:latest

variables:
  IMAGE: "${CI_REGISTRY}/${CI_REGISTRY_ID}/${CI_PROJECT_NAME}"

build:
    stage: build
    services:
        - docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_TLS_CERTDIR: ""
    before_script:
        - sleep 20
        - echo -n "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    script:
        - TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}
        - docker build . -t "${IMAGE}:${TAG}"
        - docker push ${IMAGE}:${TAG}
        - echo "TAG=$TAG" > build.env
    artifacts:
        reports:
            dotenv: build.env
    tags:
        - docker

include:
    - charts/samplefe/.gitlab-jobs/.gitlab-ci.yml