stages:
    - build
    - deploy dev

image: docker:latest

build:
    stage: build
    services:
        - docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_TLS_CERTDIR: ""
    before_script:
        - sleep 20
        - echo -n "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password $REGISTRY_PASSWORD $REGISTRY
    script:
        - docker build . -t "${REGISTRY}/${REGISTRY_ID}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
        - docker push ${REGISTRY}/${REGISTRY_ID}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
    tags:
        - docker

deploy:
    stage: deploy dev
    trigger:
      project: morgot/charts
      branch: main
      strategy: depend