stages:
    - build
    - test
    - deploy

image: docker:latest

build:
    stage: build
    services:
        - docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_TLS_CERTDIR: ""
    before_script:
        - sleep 20
        - echo -n "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    script:
        - TAG=${CI_COMMIT_TAG:-latest}
        # - docker build . -t "${CI_REGISTRY}/${CI_REGISTRY_ID}/${CI_PROJECT_NAME}:${TAG}"
        # - docker push "${CI_REGISTRY}/${CI_REGISTRY_ID}/${CI_PROJECT_NAME}:${TAG}"
        - echo "$TAG" > tag
    artifacts:
        paths:
            - tag
    tags:
        - docker

deploy:
  stage: deploy
  variables:
      ENV: 'DEV'
  trigger:
    project: morgot/charts
    branch: main
    strategy: depend
  needs:
    - build