apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sample-fe
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.samplefe.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.samplefe.service.name }}
                port:
                  number: {{ .Values.samplefe.service.port }}
