apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.samplefe.service.name }}
spec:
  selector:
    app: {{ .Values.samplefe.selector }}
  ports:
    - name: samplefe
      protocol: TCP
      port: {{ .Values.samplefe.service.port }}
      targetPort: {{ .Values.samplefe.service.targetPort }}