.prepare_helm_dependencies:
  image:
    name: alpine/helm
    entrypoint: [""]
  script:
    - export KUBECONFIG=$KUBECONFIG
  dependencies:
    - build
  tags:
    - docker

dev:
  stage: deploy
  variables:
    NAMESPACE: dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
    - when: never
  extends: .prepare_helm_dependencies
  script:
    - helm upgrade $CI_PROJECT_NAME charts/$CI_PROJECT_NAME/
      --debug
      --install
      --atomic
      --values charts/$CI_PROJECT_NAME/$NAMESPACE-values.yaml
      --namespace $NAMESPACE
      --set samplefe.image.tag=$TAG

prod:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  variables:
    NAMESPACE: prod
  extends: .prepare_helm_dependencies
  script:
    - helm upgrade $CI_PROJECT_NAME charts/$CI_PROJECT_NAME/
      --debug
      --install
      --atomic
      --values charts/$CI_PROJECT_NAME/$NAMESPACE-values.yaml
      --namespace $NAMESPACE
      --set samplefe.image.tag=$TAG
  when: manual