.prepare_helm_dependencies:
  image:
    name: alpine/helm
    entrypoint: [""]
  script:
    - export KUBECONFIG=$KUBECONFIG
  dependencies:
    - build
  tags:
    - docker

dev:
  stage: deploy
  image:
    name: alpine/helm
    entrypoint: [""]
  variables:
    NAMESPACE: dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
    - when: never
  # extends: .prepare_helm_dependencies
  before_script:
    - export KUBECONFIG=$KUBECONFIG
  script:
    - helm upgrade $CI_PROJECT_NAME charts/$CI_PROJECT_NAME/
      --debug
      --install
      --atomic
      --values charts/$CI_PROJECT_NAME/$NAMESPACE-values.yaml
      --namespace $NAMESPACE
      --set samplefe.image.tag=$TAG
  tags:
    - docker

prod:
  stage: deploy
  image:
    name: alpine/helm
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: manual
    - when: never
  variables:
    NAMESPACE: prod
  # extends: .prepare_helm_dependencies
  before_script:
    - export KUBECONFIG=$KUBECONFIG
  script:
    - helm upgrade $CI_PROJECT_NAME charts/$CI_PROJECT_NAME/
      --debug
      --install
      --atomic
      --values charts/$CI_PROJECT_NAME/$NAMESPACE-values.yaml
      --namespace $NAMESPACE
      --set samplefe.image.tag=$TAG
  tags:
    - docker