.prepare_helm_dependencies:
  image:
    name: alpine/helm
    entrypoint: [""]
  script:
    - export KUBECONFIG=$KUBECONFIG
  dependencies:
    - build
  tags:
    - docker

dev:
  stage: deploy
  variables:
    NAMESPACE: dev
  extends: .prepare_helm_dependencies
  script:
    - helm upgrade $CI_PROJECT_NAME charts/$CI_PROJECT_NAME/
      --debug
      --install
      --atomic
      --values charts/$CI_PROJECT_NAME/$NAMESPACE-values.yaml
      --namespace $NAMESPACE
      --set samplefe.image.tag=$tag
  only:
    - develop

prod:
  stage: deploy
  variables:
    NAMESPACE: prod
  extends: .prepare_helm_dependencies
  script:
    - helm upgrade $CI_PROJECT_NAME charts/$CI_PROJECT_NAME/
      --debug
      --install
      --atomic
      --values charts/$CI_PROJECT_NAME/$NAMESPACE-values.yaml
      --namespace $NAMESPACE
      --set samplefe.image.tag=$tag
  only:
    - tags
    - main