deploy_dev:
  stage: deploy
  image:
    name: alpine/helm
    entrypoint: [""]
  before_script:
    - export KUBECONFIG=$KUBECONFIG
  script:
      - helm upgrade $CI_PROJECT_NAME charts/$CI_PROJECT_NAME/
        --debug
        --install
        --atomic
        --values samplefe/dev.yaml
        --namespace dev
        --set samplefe.image.tag=$TAG
  tags:
      - docker