deploy_dev:
  stage: deploy
  variables:
    NAMESPACE: dev
  image:
    name: alpine/helm
    entrypoint: [""]
  before_script:
    - export KUBECONFIG=$KUBECONFIG
  script:
      - helm upgrade $CI_PROJECT_NAME charts/$CI_PROJECT_NAME/
        --debug
        --install
        --atomic
        --values charts/$CI_PROJECT_NAME/dev.yaml
        --namespace $NAMESPACE
        --set samplefe.image.tag=1.0.4
  tags:
      - docker